
class Length:
    AUTHOR_LENGTH = 200
    AFFIL_LENGTH = 200
    SCOPUS_COMPLETE_LENGTH = 200
    SCOPUS_STANDARD_LENGTH = 25
class Allowance:
    SCOPUS_START_ALLOWANCE = 20000
    AUTH_START_ALLOWANCE = 5000
    AFFIL_START_ALLOWANCE = 5000
